name = "FINREP + COREP"
leis = ["5493001KJTIIGC8Y1R12", "213800WAVVOPS85N2205"]
consolidation = "CONSO+SOLO"

[[extractions]]
category = "FINREP"
module = "FINREP"
# Pour combiner plusieurs module_id dans une seule extraction :
# module = ["FINREP", "FINREP_%", "%COREP%"]
templates = ["F_01.01"]
history_years = 4
frequency = "QUARTERLY"

[[extractions]]
category = "COREP"
module = "COREP"
templates = ["C_08.01"]
history_years = 2
frequency = "QUARTERLY"

[[extractions]]
category = "COREP"
module = "COREP"
templates = ["C_18.00"]
history_years = 1
frequency = "MONTHLY"
